import dotenv from "dotenv"

dotenv.config()

export const envVars = {

JWT_ACCESS_SECRET :process.env.JWT_ACCESS_SECRET!,
JWT_REFRESH_SECRET : process.env.JWT_REFRESH_SECRET!,
JWT_ACCESS_EXPIRES: process.env.JWT_ACCESS_EXPIRES,
JWT_REFRESH_EXPIRES:process.env.JWT_REFRESH_EXPIRES,

CLIENT_URL:process.env.CLIENT_URL,

GOOGLE_CLIENT_ID:process.env.GOOGLE_CLIENT_ID,
GOOGLE_CLIENT_SECRET:process.env.GOOGLE_CLIENT_SECRET,
GOOGLE_CALLBACK_URL:process.env.GOOGLE_CALLBACK_URL

}